project:
  type: website
  output-dir: docs

website:
  title: "epiworldR at InsightNet 2026"
  repo-subdir: docs
  repo-url: https://github.com/EpiForeSITE/epiworld-insightnet2026
  repo-branch: main
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction
      - href: seir.qmd
        text: SEIR model
      - href: mixing.qmd
        text: Mixing model
    right: 
      - text: More examples
        menu:
          - href: idcup.qmd
            text: IDCup Measles
          - href: model-builder.qmd
            text: Model Builder
      - href: https://github.com/EpiForeSITE/epiworld-insightnet2026
        text: "GitHub"
        icon: github

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathml
    mermaid: 
      theme: neutral
    bibliography: references.bib
